export const engineersByBranch = {
  DAMOH: ["RAVI CHAURASIYA", "JEETESH VISHWAKARMA"],
  SEONI: ["SANTRAM PANCHESHWAR", "ROHIT SHRIVASTAVA", "KOUSHAL VISHWAKARMA", "DHARMENDRA PRAJAPATI", "VIJAY KHAIRWAR", "SHIVAM CHOUDHARY", "SAURAV BAGHEL"],
  ANUPPUR: ["MAHENDRA KUSHWAHA", "RAMANUJ YADAV", "BRAJENDRA KUMAR JOGI", "MD TOUSEEF AHMED"],
  BALAGHAT: ["LEKHRAM MANESHWAR", "KISHOR BISEN", "SHISHUPAL BISEN", "MOHIT PATLE", "SHIV PRASAD RAUT", "AMAN GANVEER", "SURESH BANOTE", "SUNIL NAGRIKAR", "DUSHYANT RINAYAT"],
  KATNI: ["PRADEEP DWIVEDI", "LOVEKESH RAI", "LAVKUSH MISHRA", "KAUSHAL KISHOR VISHWAKARMA", "BALJI SINGH PARIHAR", "ANUJ DUBEY", "PAWAN PATEL", "IBRAN KHAN"],
  "JABALPUR BHL": ["ADITYA TILAK", "ANIL DEHARIYA", "ANKIT VISHWAKARMA", "ABHISHEK KANOJIYA", "BRAJESH PATEL", "DEEPAK NAMDEO", "JAIVEER SAINI", "PIYUSH PATEL", "PRAKASH SHRIVAS", "RAHUL JOUNJARD", "SACHIN NAMDEO", "RAJESH BAIN", "SAT SINGH PAL", "SOURABH SEN", "TUSHAR THAPA", "VIMAL GOTIYA", "PRADEEP SEN", "SHYAM SHIVVEDI", "RAHUL DHAWAN", "SHOBHIT LAKHERA"],
  MANDLA: ["DEVENDRA DIWAN", "NITESH RAGHUVANSHI", "DHARMENDRA CHOUDHARY"],
  NARSINGHPUR: ["JITENDRA SONI", "HARI SHANKAR MALVIYA"],
  DINDORI: ["PUNEET YADAV", "RAKESH YADAV"],
  "JABALPUR HL": ["MO. REZWAN", "DURGESH PAWAR", "RAJESH GUPTA", "PAWAN UPADHYAY", "VIKESH RAHANGDALE", "SUBHASH PRAJAPATI", "LALIT THAKRE", "SUKANTA KUMAR DAS", "ANKIT DAS", "AVINASH KUMAR THAKUR"]
} as const;

export type Branch = keyof typeof engineersByBranch;
