insert into public.branches (code, name)
values
  ('DAMOH','DAMOH'),
  ('SEONI','SEONI'),
  ('ANUPPUR','ANUPPUR'),
  ('BALAGHAT','BALAGHAT'),
  ('KATNI','KATNI'),
  ('JABALPUR_BHL','JABALPUR BHL'),
  ('MANDLA','MANDLA'),
  ('NARSINGHPUR','NARSINGHPUR'),
  ('DINDORI','DINDORI'),
  ('JABALPUR_HL','JABALPUR HL')
on conflict (name) do nothing;

with roster(branch_name, engineer_name) as (
  values
  ('DAMOH','RAVI CHAURASIYA'),('DAMOH','JEETESH VISHWAKARMA'),
  ('SEONI','SANTRAM PANCHESHWAR'),('SEONI','ROHIT SHRIVASTAVA'),('SEONI','KOUSHAL VISHWAKARMA'),('SEONI','DHARMENDRA PRAJAPATI'),('SEONI','VIJAY KHAIRWAR'),('SEONI','SHIVAM CHOUDHARY'),('SEONI','SAURAV BAGHEL'),
  ('ANUPPUR','MAHENDRA KUSHWAHA'),('ANUPPUR','RAMANUJ YADAV'),('ANUPPUR','BRAJENDRA KUMAR JOGI'),('ANUPPUR','MD TOUSEEF AHMED'),
  ('BALAGHAT','LEKHRAM MANESHWAR'),('BALAGHAT','KISHOR BISEN'),('BALAGHAT','SHISHUPAL BISEN'),('BALAGHAT','MOHIT PATLE'),('BALAGHAT','SHIV PRASAD RAUT'),('BALAGHAT','AMAN GANVEER'),('BALAGHAT','SURESH BANOTE'),('BALAGHAT','SUNIL NAGRIKAR'),('BALAGHAT','DUSHYANT RINAYAT'),
  ('KATNI','PRADEEP DWIVEDI'),('KATNI','LOVEKESH RAI'),('KATNI','LAVKUSH MISHRA'),('KATNI','KAUSHAL KISHOR VISHWAKARMA'),('KATNI','BALJI SINGH PARIHAR'),('KATNI','ANUJ DUBEY'),('KATNI','PAWAN PATEL'),('KATNI','IBRAN KHAN'),
  ('JABALPUR BHL','ADITYA TILAK'),('JABALPUR BHL','ANIL DEHARIYA'),('JABALPUR BHL','ANKIT VISHWAKARMA'),('JABALPUR BHL','ABHISHEK KANOJIYA'),('JABALPUR BHL','BRAJESH PATEL'),('JABALPUR BHL','DEEPAK NAMDEO'),('JABALPUR BHL','JAIVEER SAINI'),('JABALPUR BHL','PIYUSH PATEL'),('JABALPUR BHL','PRAKASH SHRIVAS'),('JABALPUR BHL','RAHUL JOUNJARD'),('JABALPUR BHL','SACHIN NAMDEO'),('JABALPUR BHL','RAJESH BAIN'),('JABALPUR BHL','SAT SINGH PAL'),('JABALPUR BHL','SOURABH SEN'),('JABALPUR BHL','TUSHAR THAPA'),('JABALPUR BHL','VIMAL GOTIYA'),('JABALPUR BHL','PRADEEP SEN'),('JABALPUR BHL','SHYAM SHIVVEDI'),('JABALPUR BHL','RAHUL DHAWAN'),('JABALPUR BHL','SHOBHIT LAKHERA'),
  ('MANDLA','DEVENDRA DIWAN'),('MANDLA','NITESH RAGHUVANSHI'),('MANDLA','DHARMENDRA CHOUDHARY'),
  ('NARSINGHPUR','JITENDRA SONI'),('NARSINGHPUR','HARI SHANKAR MALVIYA'),
  ('DINDORI','PUNEET YADAV'),('DINDORI','RAKESH YADAV'),
  ('JABALPUR HL','MO. REZWAN'),('JABALPUR HL','DURGESH PAWAR'),('JABALPUR HL','RAJESH GUPTA'),('JABALPUR HL','PAWAN UPADHYAY'),('JABALPUR HL','VIKESH RAHANGDALE'),('JABALPUR HL','SUBHASH PRAJAPATI'),('JABALPUR HL','LALIT THAKRE'),('JABALPUR HL','SUKANTA KUMAR DAS'),('JABALPUR HL','ANKIT DAS'),('JABALPUR HL','AVINASH KUMAR THAKUR')
)
insert into public.engineers (full_name, home_branch_id)
select r.engineer_name, b.id
from roster r
join public.branches b on b.name = r.branch_name
where not exists (
  select 1 from public.engineers e
  where e.full_name = r.engineer_name and e.home_branch_id = b.id
);
